# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9eb17b749de213a87645ae9f118a3d822a76fa3d3be35c5c62b656ccd16727b2ed18ce8185cf00d0c4d61b2a8300552af880fa427698a43f2d70148d68a638

test:
  secret_key_base: 7cbf75882964440b47b5f30295e7f7c353aeae00b2d52af45d58498db4351855e2fe5255ade6d91013035e490b5b5c15cbb056dae0bd2988af0e49370f120603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
